language: php
php:
    - '7.2'
sudo: false
branches:
  only:
  - master
#addons:
#  mariadb: '10.2'
env:
# in sequence :
# get the directory name after the sign "-"
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags" displays the last tag's shortname
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags" displays the last tag's first line
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags" displays the last tag's 3d line and following ones
>
    - GLPI_PLUGIN_NAME=`echo $TRAVIS_BUILD_DIR | sed -e 's/^.*-//'`
      TRAVIS_TAG=`git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags`
      RELEASE_NAME=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags`
      RELEASE_BODY=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags`
install: true
script: true
after_success:
    - tar --transform "s%^%$GLPI_PLUGIN_NAME/%" --show-transformed -zcvf $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz ajax front inc locales sql *.png *.xml *.php  LICENSE README.md
deploy:
  provider: releases
  api_key:
    secure: PKgVwm0sUJgxGZt6vW2ZUYZwknsaVJTy+EJzoLRHfSlgSjz/vYc/03XjERO1c6zDNi9tqnt2sIlN37US9WBZhjc6QnXBliUMJWKMz36DUttLMlD1kebLenYhYh/WW0Jo9A0t8QRFIQFsj7rH6z3FnGY5ZPgTaqi/G8YqN9ORwP+gP3gdOmCJ9SLhCH+WkhabPA3nz74GcKu+hN6In9aWq6h9+I5UP+3ICyx+/Jo6TdThk5L8fu6yPYGBvlCRLEaMGm4MZFcOQrag4pwDu8pRq4hpaQ3KJRIkbncTWXHh4NNliWhe1CT4T+aXEeVHrc5gMc0Tp7MD/9yCPaavzVMbYn06yVTEUes7oRww1etI4LD8NxosxS8m/qnbWIMz7UYORANIJwTiGsIkhZFipxcFVavGe1GZBvfagwd22txAQOMV4JAfYk8xu6KGB5UoBk4Jl/zwsSE75VMV7t2UUnMAXG2in0K7cBMSkmsBYDxwFDoISgmjbuhdqEkjwZiL/YFCwis/cjGbOy0HEUXlWPfoRBup53JzbHJ7yr+nC03jUQX2KGGnXs/500URPC5RrOF3uASeaS/Ep9FBuCnhGLJjdfu52kzR2aek3VXS4KKWG/ylSPUTp8Ln4C8iFnnCj0vkvjvkUOKzv175gs8upAEnu8+EsIXy4Y1gllJmiD6byXA=
  skip_cleanup: true
  file: $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  name: $RELEASE_NAME
  body: $RELEASE_BODY
  prerelease: false
  on:
    repo: ericferon/glpi-$GLPI_PLUGIN_NAME
    tags: true
